Cleaned up dev branch
cidgoh/nf-seqqc pull request #60
Opened 2024-03-12 18:13 UTC by anwarMZ

2024-03-18 05:09 UTC, jimmyliu1326 requested changes

2024-04-02 20:45 UTC, anwarMZ commented on workflows/seqqc.nf
> +}
done with resolved with [c846e41](https://github.com/cidgoh/nf-seqqc/pull/60/commits/c846e4173e5ce41fcda8fc9d5a8645daea69dc32)

2024-04-02 20:48 UTC, anwarMZ commented on README.md
> +1. Seqqc
resolved with [dee508d](https://github.com/cidgoh/nf-seqqc/pull/60/commits/dee508df1a7ef4894904ab069debc3b082683749)

2024-04-02 20:48 UTC, anwarMZ commented on README.md
> +2. Annotation
resolved with [dee508d](https://github.com/cidgoh/nf-seqqc/pull/60/commits/dee508df1a7ef4894904ab069debc3b082683749)

2024-04-03 23:36 UTC, jimmyliu1326 approved these changes

2024-04-04 17:28 UTC, merged